# Generated by Django 3.2.7 on 2021-09-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0005_auto_20210920_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusEdge',
            fields=[
                ('edge_id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('polyline', models.TextField()),
                ('end_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_end', to='nodes.busstop')),
                ('start_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_start', to='nodes.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='WalkEdge',
            fields=[
                ('edge_id', models.IntegerField(primary_key=True, serialize=False)),
                ('end_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_end', to='nodes.node')),
                ('start_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_start', to='nodes.node')),
            ],
        ),
        migrations.CreateModel(
            name='BusService',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=5)),
                ('edge_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routes.busedge')),
            ],
        ),
        migrations.AddConstraint(
            model_name='walkedge',
            constraint=models.UniqueConstraint(fields=('start_id', 'end_id'), name='walk edges are unique'),
        ),
        migrations.AddConstraint(
            model_name='busedge',
            constraint=models.UniqueConstraint(fields=('start_id', 'end_id'), name='bus edges are unique'),
        ),
    ]
