# Generated by Django 3.2.7 on 2021-09-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_busservice_edge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busservice',
            name='edge_id',
        ),
        migrations.RemoveField(
            model_name='walkedge',
            name='end_id',
        ),
        migrations.RemoveField(
            model_name='walkedge',
            name='start_id',
        ),
        migrations.DeleteModel(
            name='BusEdge',
        ),
        migrations.DeleteModel(
            name='BusService',
        ),
        migrations.DeleteModel(
            name='WalkEdge',
        ),
    ]
