# Generated by Django 3.2.7 on 2021-09-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='busedge',
            name='bus edges are unique',
        ),
        migrations.RemoveConstraint(
            model_name='walkedge',
            name='walk edges are unique',
        ),
        migrations.RenameField(
            model_name='busedge',
            old_name='end_id',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='busedge',
            old_name='edge_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='busedge',
            old_name='start_id',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='busservice',
            old_name='edge_id',
            new_name='edge',
        ),
        migrations.RenameField(
            model_name='busservice',
            old_name='service_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='walkedge',
            old_name='end_id',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='walkedge',
            old_name='edge_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='walkedge',
            old_name='start_id',
            new_name='start',
        ),
        migrations.AddConstraint(
            model_name='busedge',
            constraint=models.UniqueConstraint(fields=('start', 'end'), name='bus edges are unique'),
        ),
        migrations.AddConstraint(
            model_name='walkedge',
            constraint=models.UniqueConstraint(fields=('start', 'end'), name='walk edges are unique'),
        ),
    ]
