# Generated by Django 3.2.7 on 2021-09-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0004_auto_20210918_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.DecimalField(decimal_places=0, max_digits=21, unique=True)),
                ('walking_speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.node')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddIndex(
            model_name='recent',
            index=models.Index(fields=['user_id', '-access_time'], name='users_recen_user_id_8c09a8_idx'),
        ),
    ]
