# Generated by Django 3.2.7 on 2021-09-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recent',
            name='node_id',
        ),
        migrations.AddField(
            model_name='recent',
            name='route',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
