# Generated by Django 3.2.7 on 2021-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210919_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='walking_speed',
            field=models.FloatField(),
        ),
    ]
