# Generated by Django 3.2.7 on 2021-09-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_auto_20210920_0504'),
        ('users', '0003_alter_user_walking_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent',
            name='end_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='nodes.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recent',
            name='start_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='nodes.node'),
            preserve_default=False,
        ),
    ]
