# Generated by Django 3.2.7 on 2021-09-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nodes.node')),
                ('stop_duration', models.IntegerField()),
            ],
            bases=('nodes.node',),
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nodes.node')),
            ],
            bases=('nodes.node',),
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nodes.node')),
            ],
            bases=('nodes.node',),
        ),
        migrations.CreateModel(
            name='BusEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('polyline', models.TextField()),
                ('end_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_end', to='nodes.node')),
                ('start_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_start', to='nodes.node')),
            ],
        ),
        migrations.CreateModel(
            name='WalkEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_end', to='nodes.busstop')),
                ('start_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_start', to='nodes.landmark')),
            ],
        ),
        migrations.AddConstraint(
            model_name='busedge',
            constraint=models.UniqueConstraint(fields=('start_id', 'end_id'), name='bus edges are unique'),
        ),
        migrations.AddConstraint(
            model_name='walkedge',
            constraint=models.UniqueConstraint(fields=('start_id', 'end_id'), name='walk edges are unique'),
        ),
    ]
