# Generated by Django 3.2.7 on 2021-09-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_busservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busservice',
            name='edge_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodes.busedge'),
        ),
    ]
