# Generated by Django 3.2.7 on 2021-09-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_auto_20210918_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busservice',
            name='edge_id',
        ),
        migrations.RemoveField(
            model_name='walkedge',
            name='end_id',
        ),
        migrations.RemoveField(
            model_name='walkedge',
            name='start_id',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.DeleteModel(
            name='BusEdge',
        ),
        migrations.DeleteModel(
            name='BusService',
        ),
        migrations.DeleteModel(
            name='WalkEdge',
        ),
    ]
