# Generated by Django 3.2.7 on 2021-09-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
        ('routes', '0003_auto_20210920_0446'),
        ('nodes', '0005_auto_20210920_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='node_ptr',
        ),
        migrations.RemoveField(
            model_name='road',
            name='node_ptr',
        ),
        migrations.DeleteModel(
            name='BusStop',
        ),
        migrations.DeleteModel(
            name='Landmark',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
