# Generated by Django 3.2.7 on 2021-09-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_auto_20210920_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('node_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='busstop_id', serialize=False, to='nodes.node')),
                ('stop_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('node_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='landmark_id', serialize=False, to='nodes.node')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('node_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='road_id', serialize=False, to='nodes.node')),
            ],
        ),
    ]
