# Generated by Django 3.2.7 on 2021-09-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_busstop_landmark_road'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='node_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='node_id',
        ),
        migrations.RemoveField(
            model_name='road',
            name='node_id',
        ),
        migrations.AddField(
            model_name='busstop',
            name='node',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodes.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landmark',
            name='node',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodes.node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='road',
            name='node',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodes.node'),
            preserve_default=False,
        ),
    ]
